/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2022-06-28 09:01:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.home.daily_002dreport;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/home/daily-report/../common/header.jsp", Long.valueOf(1656406589051L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655038649769L));
    _jspx_dependants.put("/WEB-INF/views/home/daily-report/../common/footer.jsp", Long.valueOf(1645939795641L));
    _jspx_dependants.put("jar:file:/E:/eclipse_project/YiQingManageSystem/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/YiQingManageSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>社区疫情管理系统</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/home/layui/css/layui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/home/css/global.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"fly-header layui-bg-black\">\r\n");
      out.write("    <div class=\"layui-container\">\r\n");
      out.write("        <a class=\"fly-logo\" href=\"../system/index\" style=\"top:12px;\">\r\n");
      out.write("            <h3 style=\"color:white; padding-top:8px;\">社区疫情管理系统</h3>          \r\n");
      out.write("        </a>\r\n");
      out.write("        <ul class=\"layui-nav fly-nav-user\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"fly-panel fly-column\">\r\n");
      out.write("    <div class=\"layui-container\">\r\n");
      out.write("        <ul class=\"layui-clear\">\r\n");
      out.write("            <li id=\"system\" class=\"layui-hide-xs\"><a href=\"../system/index\">首页</a></li>\r\n");
      out.write("            <li id=\"map\"><a href=\"../maps/index\">疫情地图</a></li>\r\n");
      out.write("            <li id=\"daily-report\"><a href=\"../daily-report/index\">日常打卡</a></li>\r\n");
      out.write("            <li id=\"good-apply\"><a href=\"../good-apply/index\">物资申请</a></li>\r\n");
      out.write("            <li id=\"map\"><a href=\"../maps/index\">全国疫情</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"fly-column-right layui-hide-xs\">\r\n");
      out.write("            <span class=\"fly-search\"><i class=\"layui-icon\"></i></span>\r\n");
      out.write("            <a href=\"../daily-report/index\" class=\"layui-btn\">日常打卡</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"../../resources/home/layui/jquery.min.1.8.2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(function () {\r\n");
      out.write("       var url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("       switch (url) {\r\n");
      out.write("            case \"system\":\r\n");
      out.write("                $(\"#system\").addClass(\"layui-this\");\r\n");
      out.write("                break;\r\n");
      out.write("            case \"map\":\r\n");
      out.write("                $(\"#map\").addClass(\"layui-this\");\r\n");
      out.write("                break;\r\n");
      out.write("           case \"clue\":\r\n");
      out.write("               $(\"#clue\").addClass(\"layui-this\");\r\n");
      out.write("               break;\r\n");
      out.write("           case \"daily-report\":\r\n");
      out.write("               $(\"#daily-report\").addClass(\"layui-this\");\r\n");
      out.write("               break;\r\n");
      out.write("           case \"good-apply\":\r\n");
      out.write("               $(\"#good-apply\").addClass(\"layui-this\");\r\n");
      out.write("               break;\r\n");
      out.write("       }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function logout() {\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url:'../user/logout',\r\n");
      out.write("            dataType:'json',\r\n");
      out.write("            type:'post',\r\n");
      out.write("            data:{},\r\n");
      out.write("            success:function(result){\r\n");
      out.write("                if(result.code === 0){\r\n");
      out.write("                    window.location.href = \"../system/index\";\r\n");
      out.write("                }else{\r\n");
      out.write("                    layer.alert(result.msg, {icon: 5});\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error:function(){\r\n");
      out.write("                layer.alert(\"网络错误，退出登录失败！\", {icon: 5});\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layui-container fly-marginTop\">\r\n");
      out.write("    <div class=\"fly-panel\" pad20 style=\"padding-top: 5px;\">\r\n");
      out.write("        <div class=\"layui-form layui-form-pane\">\r\n");
      out.write("            <div class=\"layui-tab layui-tab-brief\" lay-filter=\"user\">\r\n");
      out.write("                <ul class=\"layui-tab-title\">\r\n");
      out.write("                    <li class=\"layui-this\">日常打卡</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"layui-form layui-tab-content\" id=\"LAY_ucm\" style=\"padding: 20px 0;\">\r\n");
      out.write("                    <div class=\"layui-tab-item layui-show\">\r\n");
      out.write("                        <form id=\"daily-report-form\">\r\n");
      out.write("                            <input type=\"hidden\" id=\"daily-report-id\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyReport.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                            <div class=\"layui-row layui-col-space15 layui-form-item\">\r\n");
      out.write("                                <div class=\"layui-col-md12\">\r\n");
      out.write("                                    <label for=\"location\" class=\"layui-form-label\">打卡位置</label>\r\n");
      out.write("                                    <div class=\"layui-input-block\" style=\"position: relative\">\r\n");
      out.write("                                        <input type=\"text\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyReport.location}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"location\" name=\"location\" autocomplete=\"off\" class=\"layui-input\" style=\"width: 80%\">\r\n");
      out.write("                                        <input type=\"button\" class=\"layui-input\" onclick=\"getNowLocation()\" style=\"width: 20%; position: absolute; left:815px; top:0px; cursor: pointer\" value=\"获取当前打卡位置\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"layui-row layui-col-space15 layui-form-item\">\r\n");
      out.write("                                <div class=\"layui-col-md12\">\r\n");
      out.write("                                    <label class=\"layui-form-label\">健康状态</label>\r\n");
      out.write("                                    <div class=\"layui-input-block\">\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"layui-form-item layui-form-text\">\r\n");
      out.write("                                <div class=\"layui-input-block\">\r\n");
      out.write("                                    <textarea id=\"note\" name=\"note\" placeholder=\"请输入备注...\" class=\"layui-textarea\" style=\"height: 260px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyReport.note}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"layui-form-item\">\r\n");
      out.write("                            <button class=\"layui-btn\" onclick=\"submitDailyReport()\">提交打卡</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"fly-footer\">\r\n");
      out.write("    <p> 2021-2022 &copy; 社区疫情管理系统</p>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"../../resources/home/layui/jquery.min.1.8.2.js\"></script>\r\n");
      out.write("<script src=\"../../resources/home/layui/layui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    layui.cache.page = '';\r\n");
      out.write("    layui.cache.user = {\r\n");
      out.write("        username: '游客'\r\n");
      out.write("        ,uid: -1\r\n");
      out.write("        ,avatar: '../../resources/blog/images/avatar/00.jpg'\r\n");
      out.write("        ,experience: 83\r\n");
      out.write("        ,sex: '男'\r\n");
      out.write("    };\r\n");
      out.write("    layui.config({\r\n");
      out.write("        version: \"3.0.0\"\r\n");
      out.write("        ,base: '../../resources/home/mods/'\r\n");
      out.write("    }).extend({\r\n");
      out.write("        fly: 'index'\r\n");
      out.write("    }).use('fly');\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"//api.map.baidu.com/api?v=2.0&ak=3tmfIS3gu3iSwpibAgXvIrvFx28mklvm\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    function submitDailyReport() {\r\n");
      out.write("        var data = serializeRemoveNull($(\"#daily-report-form\").serialize());\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url:'../daily-report/save',\r\n");
      out.write("            dataType:'json',\r\n");
      out.write("            type:'post',\r\n");
      out.write("            data:data,\r\n");
      out.write("            success:function(result){\r\n");
      out.write("                if(result.code === 0){\r\n");
      out.write("                    layer.alert(result.msg, {icon: 6}, function () {\r\n");
      out.write("                        window.location.href = \"../user/daily-report\";\r\n");
      out.write("                    });\r\n");
      out.write("                }else{\r\n");
      out.write("                    layer.alert(result.msg, {icon: 5});\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error:function(){\r\n");
      out.write("                layer.alert(\"网络错误，日常打卡失败！\", {icon: 5});\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function serializeRemoveNull(serStr){\r\n");
      out.write("        return serStr.split(\"&\").filter(str => !str.endsWith(\"=\")).join(\"&\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    var id;\r\n");
      out.write("    function getNowLocation() {\r\n");
      out.write("        id = layer.msg('正在获取当前位置...请稍后....', {\r\n");
      out.write("            shade: 0.4,\r\n");
      out.write("            time:false //取消自动关闭\r\n");
      out.write("        });\r\n");
      out.write("        if (navigator.geolocation) {\r\n");
      out.write("            navigator.geolocation.getCurrentPosition(locationSuccess, locationError, {\r\n");
      out.write("                // 指示浏览器获取高精度的位置，默认为false\r\n");
      out.write("                enableHighAccuracy: true,\r\n");
      out.write("                // 指定获取地理位置的超时时间，默认不限时，单位为毫秒\r\n");
      out.write("                timeout: 5000,\r\n");
      out.write("                // 最长有效期，在重复获取地理位置时，此参数指定多久再次获取位置。\r\n");
      out.write("                maximumAge: 3000\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        }else{\r\n");
      out.write("            alert(\"浏览器不支持Html5来获取地理位置信息\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function locationSuccess(position) {\r\n");
      out.write("        let lat = position.coords.latitude;\r\n");
      out.write("        let lng = position.coords.longitude;\r\n");
      out.write("        const pointBak = new BMap.Point(lng, lat);\r\n");
      out.write("        const convertor = new BMap.Convertor();\r\n");
      out.write("        convertor.translate([pointBak], 1, 5,function(resPoint) {\r\n");
      out.write("            if(resPoint && resPoint.points && resPoint.points.length>0){\r\n");
      out.write("                lng = resPoint.points[0].lng;\r\n");
      out.write("                lat = resPoint.points[0].lat;\r\n");
      out.write("            }\r\n");
      out.write("            console.log(\"当前位置经度为:\" + lng + \"纬度为:\" +lat);\r\n");
      out.write("            const point = new BMap.Point(lng, lat);\r\n");
      out.write("            const geo = new BMap.Geocoder();\r\n");
      out.write("            geo.getLocation(point, (rs) => {\r\n");
      out.write("                var addComp = rs.addressComponents;\r\n");
      out.write("                console.log(addComp);\r\n");
      out.write("                var result = addComp.province + addComp.city + addComp.district + addComp.street + addComp.streetNumber;\r\n");
      out.write("                console.log(\"当前的位置为:\" + result);\r\n");
      out.write("                $(\"#location\").val(result);\r\n");
      out.write("                layer.close(id);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function locationError(error) {\r\n");
      out.write("        switch(error.code) {\r\n");
      out.write("            case error.TIMEOUT:\r\n");
      out.write("                alert(\"连接超时，请重试\");\r\n");
      out.write("                break;\r\n");
      out.write("            case error.POSITION_UNAVAILABLE:\r\n");
      out.write("                alert('非常抱歉，我们暂时无法为您所在的星球提供位置服务');\r\n");
      out.write("                break;\r\n");
      out.write("            case error.PERMISSION_DENIED:\r\n");
      out.write("                alert('您拒绝了使用位置共享服务，查询已取消');\r\n");
      out.write("                break;\r\n");
      out.write("            default:\r\n");
      out.write("                alert('发生未知错误!');\r\n");
      out.write("                break;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/home/daily-report/../common/header.jsp(18,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${HOME_USER != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <li class=\"layui-nav-item\">\r\n");
          out.write("                    <a class=\"fly-nav-avatar\" href=\"../user/center\">\r\n");
          out.write("                        <cite class=\"layui-hide-xs\">欢迎您，");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${HOME_USER.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</cite>\r\n");
          out.write("                        <img src=\"../../common/file/view_photo?filename=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${HOME_USER.headPic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                    </a>\r\n");
          out.write("                    <dl class=\"layui-nav-child\">\r\n");
          out.write("                        <dd><a href=\"../user/center\"><i class=\"layui-icon\">&#xe68e;</i>用户中心</a></dd>\r\n");
          out.write("                        <hr style=\"margin: 5px 0;\">\r\n");
          out.write("                        <dd><a href=\"javascript:void(0);\" onclick=\"logout()\" style=\"text-align: center;\">退出</a></dd>\r\n");
          out.write("                    </dl>\r\n");
          out.write("                </li>\r\n");
          out.write("                <li class=\"layui-nav-item\" style=\"padding-left: 30px;\">\r\n");
          out.write("                    <a href=\"../../admin/user/login\">后台</a>\r\n");
          out.write("                </li>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/home/daily-report/../common/header.jsp(34,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${HOME_USER == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <li class=\"layui-nav-item\">\r\n");
          out.write("                    <a href=\"../system/login\">登录</a>\r\n");
          out.write("                </li>\r\n");
          out.write("                <li class=\"layui-nav-item\">\r\n");
          out.write("                    <a href=\"../system/register\">注册</a>\r\n");
          out.write("                </li>\r\n");
          out.write("                <li class=\"layui-nav-item\">\r\n");
          out.write("                    <a class=\"fly-nav-avatar\" href=\"javascript:void(0);\">\r\n");
          out.write("                        <cite class=\"layui-hide-xs\"></cite>\r\n");
          out.write("                        <img src=\"../../common/file/view_photo?filename=../resources/upload/common/no_image.jpg\">\r\n");
          out.write("                    </a>\r\n");
          out.write("                </li>\r\n");
          out.write("                <li class=\"layui-nav-item\" style=\"padding-left: 30px;\">\r\n");
          out.write("                    <a href=\"../../admin/user/login\">后台</a>\r\n");
          out.write("                </li>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/home/daily-report/index.jsp(28,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyReport.healthStatus == 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <input type=\"radio\" checked name=\"healthStatus\" value=\"1\" title=\"健康\" autocomplete=\"off\" class=\"layui-input\">\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/home/daily-report/index.jsp(31,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyReport.healthStatus != 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <input type=\"radio\" name=\"healthStatus\" value=\"1\" title=\"健康\" autocomplete=\"off\" class=\"layui-input\">\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/home/daily-report/index.jsp(34,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyReport.healthStatus == 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <input type=\"radio\" checked name=\"healthStatus\" value=\"2\" title=\"有发烧、咳嗽等症状\" autocomplete=\"off\" class=\"layui-input\">\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/home/daily-report/index.jsp(37,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyReport.healthStatus != 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <input type=\"radio\" name=\"healthStatus\" value=\"2\" title=\"有发烧、咳嗽等症状\" autocomplete=\"off\" class=\"layui-input\">\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /WEB-INF/views/home/daily-report/index.jsp(40,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyReport.healthStatus == 3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <input type=\"radio\" checked name=\"healthStatus\" value=\"3\" title=\"其他症状\" autocomplete=\"off\" class=\"layui-input\">\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /WEB-INF/views/home/daily-report/index.jsp(43,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dailyReport.healthStatus != 3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            <input type=\"radio\" name=\"healthStatus\" value=\"3\" title=\"其他症状\" autocomplete=\"off\" class=\"layui-input\">\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }
}
