/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2022-06-13 13:15:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <title>社区疫情后台管理系统</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"description\" content=\"User login page\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- bootstrap & fontawesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/admin/assets/css/bootstrap.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/admin/assets/font-awesome/4.2.0/css/font-awesome.min.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- text fonts -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/admin/assets/fonts/fonts.googleapis.com.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- ace styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/admin/assets/css/ace.min.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!--[if lte IE 9]>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/admin/assets/css/ace-part2.min.css\" />\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/admin/assets/css/ace-rtl.min.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!--[if lte IE 9]>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../resources/admin/assets/css/ace-ie.min.css\" />\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"../../resources/admin/assets/js/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"../../resources/admin/assets/js/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"login-layout blur-login\">\r\n");
      out.write("<div class=\"main-container\">\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-10 col-sm-offset-1\" style=\"margin-top:100px;\">\r\n");
      out.write("                <div class=\"login-container\">\r\n");
      out.write("                    <div class=\"center\">\r\n");
      out.write("                        <h1>\r\n");
      out.write("                            \r\n");
      out.write("                            <span class=\"white\">社区疫情</span>\r\n");
      out.write("                            <span class=\"white\" id=\"id-text2\">后台管理系统</span>\r\n");
      out.write("                        </h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"space-6\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"position-relative\">\r\n");
      out.write("                        <div id=\"login-box\" class=\"login-box visible widget-box no-border\">\r\n");
      out.write("                            <div class=\"widget-body\">\r\n");
      out.write("                                <div class=\"widget-main\">\r\n");
      out.write("                                    <h4 class=\"header blue lighter bigger\">\r\n");
      out.write("                                        \r\n");
      out.write("                                        请输入您的信息！\r\n");
      out.write("                                    </h4>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"space-6\"></div>\r\n");
      out.write("\r\n");
      out.write("                                    <form id=\"login-form\">\r\n");
      out.write("                                        <fieldset>\r\n");
      out.write("                                            <label class=\"block clearfix\">\r\n");
      out.write("                                                <span class=\"block input-icon input-icon-right\">\r\n");
      out.write("                                                    <input type=\"text\" name=\"username\" class=\"form-control\" placeholder=\"请输入用户昵称...\" />\r\n");
      out.write("                                                    <i class=\"ace-icon fa fa-user\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </label>\r\n");
      out.write("\r\n");
      out.write("                                            <label class=\"block clearfix\">\r\n");
      out.write("                                                <span class=\"block input-icon input-icon-right\">\r\n");
      out.write("                                                    <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"请输入用户密码...\" />\r\n");
      out.write("                                                    <i class=\"ace-icon fa fa-lock\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </label>\r\n");
      out.write("\r\n");
      out.write("                                            <label class=\"block clearfix\">\r\n");
      out.write("                                                <span class=\"block input-icon input-icon-right\" style=\"position: relative\">\r\n");
      out.write("                                                    <input type=\"text\" name=\"captcha\" class=\"form-control\" style=\"width:160px;\" placeholder=\"请输入验证码...\" />\r\n");
      out.write("                                                    <i class=\"ace-icon fa fa-key\" style=\"right: 133px;\"></i>\r\n");
      out.write("                                                    <img id=\"captcha-img\" title=\"点击切换验证码\" style=\"cursor:pointer;position: absolute; top:0px;left:170px;\" src=\"../../common/captcha/generate_captcha?vl=4&fs=21&w=94&h=29&method=admin_login\" width=\"120px\" height=\"34px\"  onclick=\"changeCaptcha();\">\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </label>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"space\"></div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"clearfix\">\r\n");
      out.write("\r\n");
      out.write("                                                <button type=\"button\" class=\"width-35 pull-right btn btn-sm btn-primary\" onclick=\"login()\" style=\"margin-right:90px;\">\r\n");
      out.write("                                                    <span class=\"bigger-110\">登录</span>\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"space-4\"></div>\r\n");
      out.write("                                        </fieldset>\r\n");
      out.write("                                    </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                </div><!-- /.widget-main -->\r\n");
      out.write("\r\n");
      out.write("                            </div><!-- /.widget-body -->\r\n");
      out.write("                        </div><!-- /.login-box -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div><!-- /.position-relative -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- /.col -->\r\n");
      out.write("        </div><!-- /.row -->\r\n");
      out.write("    </div><!-- /.main-content -->\r\n");
      out.write("</div><!-- /.main-container -->\r\n");
      out.write("\r\n");
      out.write("<!-- basic scripts -->\r\n");
      out.write("\r\n");
      out.write("<!--[if !IE]> -->\r\n");
      out.write("<script src=\"../../resources/admin/assets/js/jquery.2.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!--[if IE]>\r\n");
      out.write("<script src=\"../../resources/admin/assets/js/jquery.1.11.1.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!--[if !IE]> -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    window.jQuery || document.write(\"<script src='../../resources/admin/assets/js/jquery.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!--[if IE]>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    window.jQuery || document.write(\"<script src='../../resources/admin/assets/js/jquery1x.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("</script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    if('ontouchstart' in document.documentElement) document.write(\"<script src='../../resources/admin/assets/js/jquery.mobile.custom.min.js'>\"+\"<\"+\"/script>\");\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"../../resources/admin/assets/js/alert.js\"></script>\r\n");
      out.write("<!-- inline scripts related to this page -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    jQuery(function($) {\r\n");
      out.write("        $(document).on('click', '.toolbar a[data-target]', function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            var target = $(this).data('target');\r\n");
      out.write("            $('.widget-box.visible').removeClass('visible');//hide others\r\n");
      out.write("            $(target).addClass('visible');//show target\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    // 登录操作处理\r\n");
      out.write("    function login() {\r\n");
      out.write("        var data = $(\"#login-form\").serialize();\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url:'../user/login',\r\n");
      out.write("            dataType:'json',\r\n");
      out.write("            type:'post',\r\n");
      out.write("            data:data,\r\n");
      out.write("            success:function(result){\r\n");
      out.write("                if(result.code === 0){\r\n");
      out.write("                    window.location.href = '../system/index';\r\n");
      out.write("                }else {\r\n");
      out.write("                    changeCaptcha();\r\n");
      out.write("                    commonUtil.message(result.msg, 'danger');\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error:function () {\r\n");
      out.write("                changeCaptcha();\r\n");
      out.write("                commonUtil.message(\"网络错误\", 'danger');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /**\r\n");
      out.write("     *  更换验证码\r\n");
      out.write("     */\r\n");
      out.write("    function changeCaptcha(){\r\n");
      out.write("        $(\"#captcha-img\").attr(\"src\",'../../common/captcha/generate_captcha?vl=4&fs=21&w=94&h=29&method=admin_login&t=' + new Date().getTime());\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
